# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog.nathanielbd
author: nathanielbd

show_exerpts: true

theme: minima

minima:
        date_format: "%b %-d, %Y"
        social_links:
                github: nathanielbd
                linkedin: nathanielbd

email: nathanielbd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        I write about my interests and things I 
        found useful while teaching myself things.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
github_username:  nathanielbd

# Build settings
markdown: kramdown
